# Generated by Django 5.2.17 on 2026-08-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("normalized_name", models.TextField(editable=False)),
                ("address", models.TextField()),
                ("normalized_address", models.TextField(editable=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "geocode_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("unresolved", "Unresolved"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("resolved_address", models.TextField(blank=True, null=True)),
                ("geocode_error", models.TextField(blank=True, null=True)),
                ("geocode_attempted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "solar_resource_status",
                    models.CharField(
                        choices=[
                            ("blocked", "Blocked"),
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="blocked",
                        max_length=9,
                    ),
                ),
                ("annual_ghi_kwh_m2_day", models.FloatField(blank=True, null=True)),
                ("annual_dni_kwh_m2_day", models.FloatField(blank=True, null=True)),
                (
                    "annual_latitude_tilt_kwh_m2_day",
                    models.FloatField(blank=True, null=True),
                ),
                ("monthly_solar_data", models.JSONField(blank=True, null=True)),
                ("solar_resource_error", models.TextField(blank=True, null=True)),
                (
                    "solar_resource_attempted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "pvwatts_status",
                    models.CharField(
                        choices=[
                            ("blocked", "Blocked"),
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="blocked",
                        max_length=9,
                    ),
                ),
                ("pvwatts_assumptions", models.JSONField(blank=True, null=True)),
                ("annual_ac_kwh", models.FloatField(blank=True, null=True)),
                ("capacity_factor_percent", models.FloatField(blank=True, null=True)),
                (
                    "annual_solar_radiation_kwh_m2_day",
                    models.FloatField(blank=True, null=True),
                ),
                ("monthly_pvwatts_data", models.JSONField(blank=True, null=True)),
                ("pvwatts_error", models.TextField(blank=True, null=True)),
                ("pvwatts_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("id",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("normalized_name", "normalized_address"),
                        name="unique_site_normalized_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "geocode_status__in",
                                ["pending", "resolved", "unresolved", "failed"],
                            )
                        ),
                        name="site_geocode_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "solar_resource_status__in",
                                ["blocked", "pending", "succeeded", "failed"],
                            )
                        ),
                        name="site_solar_resource_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "pvwatts_status__in",
                                ["blocked", "pending", "succeeded", "failed"],
                            )
                        ),
                        name="site_pvwatts_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("geocode_attempted_at__isnull", True),
                                ("geocode_status", "pending"),
                            ),
                            models.Q(
                                ("geocode_attempted_at__isnull", False),
                                (
                                    "geocode_status__in",
                                    ("resolved", "unresolved", "failed"),
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="site_geocode_attempt_matches_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("geocode_status", "resolved"),
                            models.Q(
                                ("pvwatts_status", "blocked"),
                                ("solar_resource_status", "blocked"),
                            ),
                            _connector="OR",
                        ),
                        name="site_downstream_blocked_until_geocoded",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("solar_resource_attempted_at__isnull", True),
                                ("solar_resource_status__in", ("blocked", "pending")),
                            ),
                            models.Q(
                                ("solar_resource_attempted_at__isnull", False),
                                ("solar_resource_status__in", ("succeeded", "failed")),
                            ),
                            _connector="OR",
                        ),
                        name="site_solar_attempt_matches_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("pvwatts_attempted_at__isnull", True),
                                ("pvwatts_status__in", ("blocked", "pending")),
                            ),
                            models.Q(
                                ("pvwatts_attempted_at__isnull", False),
                                ("pvwatts_status__in", ("succeeded", "failed")),
                            ),
                            _connector="OR",
                        ),
                        name="site_pvwatts_attempt_matches_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("geocode_status", "resolved"),
                                ("latitude__isnull", False),
                                ("longitude__isnull", False),
                            ),
                            models.Q(
                                models.Q(("geocode_status", "resolved"), _negated=True),
                                ("latitude__isnull", True),
                                ("longitude__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="site_coordinates_match_geocode_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__isnull", True),
                            models.Q(("latitude__gte", -90.0), ("latitude__lte", 90.0)),
                            _connector="OR",
                        ),
                        name="site_latitude_in_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__isnull", True),
                            models.Q(
                                ("longitude__gte", -180.0), ("longitude__lte", 180.0)
                            ),
                            _connector="OR",
                        ),
                        name="site_longitude_in_range",
                    ),
                ],
            },
        ),
    ]
